# Generated by Django 3.0.6 on 2020-06-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quesion', models.CharField(max_length=400)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='canteen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quesion', models.CharField(max_length=400)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='query_table',
            name='answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='query_table',
            name='quesion',
            field=models.CharField(max_length=400),
        ),
    ]
